# The API requires specific book codes, so I have to be able to translate all of them. key -> value is the best for this.
def books_dict():
    return dict([("GENESIS", "GEN"),
                 ("EXODUS", "EXO"),
                 ("LEVITICUS", "LEV"),
                 ("NUMBERS", "NUM"),
                 ("DEUTERONOMY", "DEU"),
                 ("JOSHUA", "JOS"),
                 ("JUDGES", "JDG"),
                 ("RUTH", "RUT"),
                 ("1 SAMUEL", "1SA"),
                 ("2 SAMUEL", "2SA"),
                 ("1ST SAMUEL", "1SA"),
                 ("2ND SAMUEL", "2SA"),
                 ("1ST KINGS", "1KI"),
                 ("2ND KINGS", "2KI"),
                 ("1 KINGS", "1KI"),
                 ("2 KINGS", "2KI"),
                 ("1ST CHRONICLES", "1CH"),
                 ("2ND CHRONICLES", "2CH"),
                 ("1 CHRONICLES", "1CH"),
                 ("2 CHRONICLES", "2CH"),
                 ("EZRA", "EZR"),
                 ("NEHEMIAH", "NEH"),
                 ("ESTHER", "EST"),
                 ("JOB", "JOB"),
                 ("PSALMS", "PSA"),
                 ("PROVERBS", "PRO"),
                 ("ECCLESIASTES", "ECC"),
                 ("SONG OF SOLOMON", "SNG"),
                 ("ISAIAH", "ISA"),
                 ("JEREMIAH", "JER"),
                 ("LAMENTATIONS", "LAM"),
                 ("EZEKIEL", "EZK"),
                 ("DANIEL", "DAN"),
                 ("HOSEA", "HOS"),
                 ("JOEL", "JOL"),
                 ("AMOS", "AMO"),
                 ("OBADIAH", "OBA"),
                 ("JONAH", "JON"),
                 ("MICAH", "MIC"),
                 ("NAHUM", "NAM"),
                 ("HABAKKUK", "HAB"),
                 ("ZEPHANIAH", "ZEP"),
                 ("HAGGAI", "HAG"),
                 ("ZECHARIAH", "ZEC"),
                 ("MALACHI", "MAL"),
                 ("TOBIT", "TOB"),
                 ("JUDITH", "JDT"),
                 ("ESTHER GREEK", "ESG"),
                 ("WISDOM OF SOLOMON", "WIS"),
                 ("SIRACH", "SIR"),
                 ("BARUCH", "BAR"),
                 ("DANIEL GREEK", "DAG"),
                 ("1ST MACCABEES", "1MA"),
                 ("2ND MACCABEES", "2MA"),
                 ("1ST ESDRAS", "1ES"),
                 ("2ND ESDRAS", "2ES"),
                 ("1 MACCABEES", "1MA"),
                 ("2 MACCABEES", "2MA"),
                 ("1 ESDRAS", "1ES"),
                 ("2 ESDRAS", "2ES"),
                 ("3RD MACCABEES", "3MA"),
                 ("4TH MACCABEES", "4MA"),
                 ("PRAYER OF MANASSES", "MAN"),
                 ("3 MACCABEES", "3MA"),
                 ("4 MACCABEES", "4MA"),
                 ("PSALM 151", "PS2"),
                 ("MATTHEW", "MAT"),
                 ("MARK", "MRK"),
                 ("LUKE", "LUK"),
                 ("JOHN", "JHN"),
                 ("ACTS", "ACT"),
                 ("ROMANS", "ROM"),
                 ("1ST CORINTHIANS", "1CO"),
                 ("2ND CORINTHIANS", "2CO"),
                 ("1 CORINTHIANS", "1CO"),
                 ("2 CORINTHIANS", "2CO"),
                 ("GALATIANS", "GAL"),
                 ("EPHESIANS", "EPH"),
                 ("PHILIPPIANS", "PHP"),
                 ("COLOSSIANS", "COL"),
                 ("1ST THESSALONIANS", "1TH"),
                 ("2ND THESSALONIANS", "2TH"),
                 ("1ST TIMOTHY", "1TI"),
                 ("2ND TIMOTHY", "2TI"),
                 ("1 THESSALONIANS", "1TH"),
                 ("2 THESSALONIANS", "2TH"),
                 ("1 TIMOTHY", "1TI"),
                 ("2 TIMOTHY", "2TI"),
                 ("TITUS", "TIT"),
                 ("PHILEMON", "PHM"),
                 ("HEBREWS", "HEB"),
                 ("JAMES", "JAS"),
                 ("1ST PETER", "1PE"),
                 ("2ND PETER", "2PE"),
                 ("1ST JOHN", "1JN"),
                 ("2ND JOHN", "2JN"),
                 ("3RD JOHN", "3JN"),
                 ("1 PETER", "1PE"),
                 ("2 PETER", "2PE"),
                 ("1 JOHN", "1JN"),
                 ("2 JOHN", "2JN"),
                 ("3 JOHN", "3JN"),
                 ("JUDE", "JUD"),
                 ("REVELATION", "REV")])