# The API requires chapter codes, so I have to be able to translate all of them. key -> value is the best for this.
def chapters_dict():
    return dict([("Genesis", "GEN"),
                 ("Exodus", "EXO"),
                 ("Leviticus", "LEV"),
                 ("Numbers", "NUM"),
                 ("Deuteronomy", "DEU"),
                 ("Joshua", "JOS"),
                 ("Judges", "JDG"),
                 ("Ruth", "RUT"),
                 ("1 Samuel", "1SA"),
                 ("2 Samuel", "2SA"),
                 ("1st Samuel", "1SA"),
                 ("2nd Samuel", "2SA"),
                 ("1 Kings", "1KI"),
                 ("2 Kings", "2KI"),
                 ("1st Kings", "1KI"),
                 ("2nd Kings", "2KI"),
                 ("1 Chronicles", "1CH"),
                 ("2 Chronicles", "2CH"),
                 ("1st Chronicles", "1CH"),
                 ("2nd Chronicles", "2CH"),
                 ("Ezra", "EZR"),
                 ("Nehemiah", "NEH"),
                 ("Esther", "EST"),
                 ("Job", "JOB"),
                 ("Psalms", "PSA"),
                 ("Proverbs", "PRO"),
                 ("Ecclesiastes", "ECC"),
                 ("Song of Solomon", "SNG"),
                 ("Isaiah", "ISA"),
                 ("Jeremiah", "JER"),
                 ("Lamentations", "LAM"),
                 ("Ezekiel", "EZK"),
                 ("Daniel", "DAN"),
                 ("Hosea", "HOS"),
                 ("Joel", "JOL"),
                 ("Amos", "AMO"),
                 ("Obadiah", "OBA"),
                 ("Jonah", "JON"),
                 ("Micah", "MIC"),
                 ("Nahum", "NAM"),
                 ("Habakkuk", "HAB"),
                 ("Zephaniah", "ZEP"),
                 ("Haggai", "HAG"),
                 ("Zechariah", "ZEC"),
                 ("Malachi", "MAL"),
                 ("Tobit", "TOB"),
                 ("Judith", "JDT"),
                 ("Esther (Greek)", "ESG"),
                 ("Wisdom of Solomon", "WIS"),
                 ("Sirach", "SIR"),
                 ("Baruch", "BAR"),
                 ("Daniel (Greek)", "DAG"),
                 ("1 Maccabees", "1MA"),
                 ("2 Maccabees", "2MA"),
                 ("1st Maccabees", "1MA"),
                 ("2nd Maccabees", "2MA"),
                 ("1 Esdras", "1ES"),
                 ("2 Esdras", "2ES"),
                 ("1st Esdras", "1ES"),
                 ("2nd Esdras", "2ES"),
                 ("Prayer of Manasses", "MAN"),
                 ("3 Maccabees", "3MA"),
                 ("4 Maccabees", "4MA"),
                 ("3rd Maccabees", "3MA"),
                 ("4th Maccabees", "4MA"),
                 ("Psalm 151", "PS2"),
                 ("Matthew", "MAT"),
                 ("Mark", "MRK"),
                 ("Luke", "LUK"),
                 ("John", "JHN"),
                 ("Acts", "ACT"),
                 ("Romans", "ROM"),
                 ("1 Corinthians", "1CO"),
                 ("2 Corinthians", "2CO"),
                 ("1st Corinthians", "1CO"),
                 ("2nd Corinthians", "2CO"),
                 ("Galatians", "GAL"),
                 ("Ephesians", "EPH"),
                 ("Philippians", "PHP"),
                 ("Colossians", "COL"),
                 ("1 Thessalonians", "1TH"),
                 ("2 Thessalonians", "2TH"),
                 ("1st Thessalonians", "1TH"),
                 ("2nd Thessalonians", "2TH"),
                 ("1 Timothy", "1TI"),
                 ("2 Timothy", "2TI"),
                 ("1st Timothy", "1TI"),
                 ("2nd Timothy", "2TI"),
                 ("Titus", "TIT"),
                 ("Philemon", "PHM"),
                 ("Hebrews", "HEB"),
                 ("James", "JAS"),
                 ("1 Peter", "1PE"),
                 ("2 Peter", "2PE"),
                 ("1 John", "1JN"),
                 ("2 John", "2JN"),
                 ("3 John", "3JN"),
                 ("1st Peter", "1PE"),
                 ("2nd Peter", "2PE"),
                 ("1st John", "1JN"),
                 ("2nd John", "2JN"),
                 ("3rd John", "3JN"),
                 ("Jude", "JUD"),
                 ("Revelation", "REV")])
